start_charging:
  description: "Starts charger. Also authorizes if configured to use authorization."
  fields:
    charger_id:
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxx-yyyyyyyyyyyy"

stop_charging:
  description: "Starts charger. Also authorizes if configured to use authorization."
  fields:
    charger_id:
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxx-yyyyyyyyyyyy"

stop_pause_charging:
  description: "New stop/pause"
  fields:
    charger_id:
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxx-yyyyyyyyyyyy"

resume_charging:
  description: "New resume command."
  fields:
    charger_id:
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxx-yyyyyyyyyyyy"

update_firmware:
  description: "New resume command."
  fields:
    charger_id:
      description: "Update the firmware."
      example: "yyyyyyyy-9999-99xx-xxx-yyyyyyyyyyyy"

restart_charger:
  description: "Restart charger."
  fields:
    charger_id:
      description: "The charger id"
      example: "yyyyyyyy-9999-99xx-xxx-yyyyyyyyyyyy"

set_max_current:
  description: "Set max charging current"
  fields:
    installation_id:
      description: "The installation id"
      example: "yyyyyyyy-xxxx-xxxx-xxxx-yyyyyyyyyyyy"
    max_current:
      description: "Max charger current in amps"
      example: 32

